### PR TITLE
parameter to disable public interfaces on cluster nodes

### PR DESCRIPTION
**Pull request by derlinuxer**
Hi vitobotta,

the PR. I hope it's not complete rubbish. I really like your "hetzner-k3s" it makes me independent of the inflexible rancher create tool.

Go on please.

Stephan

### CODE REVIEW

**Comment by vitobotta** [comment]
> Hi vitobotta,
> 
> the PR. I hope it's not complete rubbish. I really like your "hetzner-k3s" it makes me independent of the inflexible rancher create tool.
> 
> Go on please.
> 
> Stephan

From a quick first look it looks good! Will test it as soon as I have time. Thanks!

**Comment by derlinuxer** [comment]
I've implemented an additional feature I really needed. To setup network via cloud init it is necessary to have pool based cloud init, because of different interface names used for different machine types. So I've implemented the cloud init (post_create_commands & additional_packages) in pool section. Now both pool and global cloud init config possible. If both is set pool config will overrule the global config.

Shell we delete current PR and I create a new one this all change?

**Comment by vitobotta** [comment]
Do these new changes override what you did in this PR? If yes then yeah, just close this PR and make a new one. Otherwise if the changes are separate just make another PR.

**Comment by derlinuxer** [comment]
yap I removed 2 not needed lines of the current PR, so I close this one and create a new PR.

**Comment by vitobotta** [comment]
👍

**Pull request closed without merging**
