### PR TITLE
Add configuration options for cluster-cidr, service-cidr and cluster-dns

### PR DESCRIPTION
**Pull request by Floppy012**
This PR adds three new options to the configuration:

- `cluster_cidr`
- `service_cidr`
- `cluster_dns`

These three options are basically just passed on to the CLI command when setting up the master.

I have compiled and tested it with a small test cluster on Hetzner. Everything seems to work.

**Please note:** This is the first time that I work with Crystal. I haven't really heard of this language before I've seen this project. So if anything is wrong, please tell me so I can fix it (and learn).

### CODE REVIEW

**Comment by salman-ahmad** [comment]
is it possible to specify CIDR for the control plane?

**Comment by Floppy012** [comment]
> This is a good change, thank you. Is it possible to specify CIDR for the control plane?

Not with the changes of this PR. I've looked around the documentation a bit and didn't find anything that would allow to change this.

**Comment by vitobotta** [comment]
Hi @Floppy012 thanks a lot for this and sorry for the delay, I have been really busy with the day job. I also forgot to check PRs before releasing a new version today. :-/

The PR looks awesome, thanks! Before I merge, are you aware of any potential side effects with these changes and k3s?

**Comment by Floppy012** [comment]
Thanks @vitobotta 

I've just noticed that the CCM deployment also has the Cluster-CIDR defined as CLI Argument. I didn't notice this as it worked fine while testing and just tested again and it doesn't seem to have any impact on the actual creation of routes as they are correct:

```
$ k -n kube-system get deployment/hcloud-cloud-controller-manager -o jsonpath='{.spec.template.spec.containers[0].command}'
["/bin/hcloud-cloud-controller-manager","--allow-untagged-cloud","--cloud-provider=hcloud","--leader-elect=false","--route-reconciliation-period=30s","--allocate-node-cidrs=true","--cluster-cidr=10.244.0.0/16"]

$ hcloud network describe network-1
ID:             ...
Name:           network-1
Created:        Tue Apr 11 13:00:57 CEST 2023 (6 days ago)
IP Range:       10.20.0.0/16
Subnets:
  - Type:               cloud
    Network Zone:       eu-central
    IP Range:           10.20.0.0/16
    Gateway:            10.20.0.1
Routes:
  - Destination:        10.21.0.0/24
    Gateway:            10.20.0.5
  - Destination:        10.21.2.0/24
    Gateway:            10.20.0.4
  - Destination:        10.21.3.0/24
    Gateway:            10.20.0.2
  - Destination:        10.21.1.0/24
    Gateway:            10.20.0.3
  - Destination:        10.21.4.0/24
    Gateway:            10.20.0.6
Protection:
  Delete:       no
Labels:
  No labels
```
But I feel not updating the CLI Arg could lead to unexpected error when Hetzner decides to use it somewhere. Shall I just manipulate it with regex or include the CCM deployment as template?

**Comment by vitobotta** [comment]
I think it's safer just in case. If you have a chance to try this other change it would be awesome, otherwise I will look into it when I have time. Thanks

**Comment by Floppy012** [comment]
@vitobotta I have included the CCM-Networks manifest as a Crinja template. It now produces a CCM manifest with the correct Cluster-CIDR. Due to the CCM having `hostNetwork: true` SonarCloud fails. I found nothing regarding ignore files for SonarCloud so you probably have to ignore the file in the settings somewhere.

Maybe that is helpful: https://docs.sonarcloud.io/advanced-setup/analysis-scope/#ignoring-issues

**Comment by vitobotta** [comment]
Hi @Floppy012 , are you still interested in completing this PR? :)

**Comment by Floppy012** [comment]
@vitobotta should be fixed now

**Comment by vitobotta** [comment]
Thanks! I will make a release soon. Thank you for your contribution :)

**Pull request merged**
