### PR TITLE
api_server_dns setting to support alternate DNS for k8s API server

### PR DESCRIPTION
**Pull request by mgalesloot**
`api_server_dns` setting to support alternate DNS for k8s API server. 

See issue https://github.com/vitobotta/hetzner-k3s/issues/238

### CODE REVIEW

**Comment by vitobotta** [comment]
Looks awesome, thanks! Do you remind renaming the setting to `api_server_hostname` since DNS might suggest that it's a DNS server setting? Thanks!

**Comment by mgalesloot** [comment]
Updated the fieldname per your recommendation.

**Comment by vitobotta** [comment]
Hi @mgalesloot, thanks a lot for the PR! Looks like a very useful change. I am planning on making a new release this coming weekend if possible.

**Comment by vitobotta** [comment]
Merged, thanks for another useful contribution!

**Pull request merged**
