### PR TITLE
enable custom url for cloud controller manager

### PR DESCRIPTION
**Pull request by DaanVanVugt**
These settings were needed for me to get a hybrid VPS & bare-metal hetzner cluster running. I made a vSwitch for the 10.0.1.0/24 subnet and changed the firewall settings also in this PR.

```yaml
private_network: 10.0.0.0/16
private_network_subnet: 10.0.0.0/24
schedule_workloads_on_masters: true
cloud_controller_manager_manifest_url: https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm.yaml
```

### CODE REVIEW

**Comment by clouedoc** [comment]
Hey Daan,

Would you mind sharing the script you used to join your dedicated node to your cluster?

I am able to connect it fine, but I end up with a NetworkUnreachable error because hetzner-cloud-controller-manager tries to create routes but fails

image

I'm wondering if there is a way to make HCCM leave my node alone?

```
I0704 17:34:57.577546       1 event.go:294] "Event occurred" object="projectcontour/envoy" fieldPath="" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBTargets: hcops/providerIDToServerID: missing prefix hcloud://: "
I0704 17:35:12.790550       1 route_controller.go:194] Creating route for node corkus-new 10.244.29.0/24 with hint 2bd3e210-bc70-4040-bfeb-dc7c3bdea9dc, throttled 13.896µs
E0704 17:35:13.332411       1 route_controller.go:218] Could not create route 2bd3e210-bc70-4040-bfeb-dc7c3bdea9dc 10.244.29.0/24 for node corkus-new: hcloud/CreateRoute: hcops/AllServersCache.ByName: corkus-new hcops/AllServersCache.getCache: not found
I0704 17:35:13.332544       1 event.go:294] "Event occurred" object="corkus-new" fieldPath="" kind="Node" apiVersion="" type="Warning" reason="FailedToCreateRoute" message="Could not create route 2bd3e210-bc70-4040-bfeb-dc7c3bdea9dc 10.244.29.0/24 for node corkus-new after 541.853528ms: hcloud/CreateRoute: hcops/AllServersCache.ByName: corkus-new hcops/AllServersCache.getCache: not found"
I0704 17:35:28.033915       1 node_controller.go:415] Initializing node corkus-new with cloud provider
E0704 17:35:28.229471       1 node_controller.go:229] error syncing 'corkus-new': failed to get instance metadata for node corkus-new: failed to get instance metadata: no matching server found for node 'corkus-new', requeuing
I0704 17:35:37.577968       1 load_balancers.go:109] "ensure Load Balancer"
```

**Comment by clouedoc** [comment]
PS: I'm using this manifest for the HCCM: `https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.15.0/ccm-networks.yaml`

**Comment by clouedoc** [comment]
It looks like I would only need to use a manifest without the networks part and I should be good?

https://github.com/syself/hetzner-cloud-controller-manager#networks-support

I will try this tomorrow; I'm too sleepy to break my cluster again tonight 🙂

**Comment by DaanVanVugt** [comment]
For me to get around this NetworkUnreachable error I installed the syself ccm-hcloud one (with Helm, not from the yaml, but you should be able to do it with a manifest file from that repository).

https://github.com/syself/hetzner-cloud-controller-manager
Also my bare-metal nodes need a `bm-` prefix in the name then.

Finally I set up a vswitch for the connection, that's why the private network size and subnet are different.

**Comment by clouedoc** [comment]
Thqnks8
- Camille



5 juil. 2023, 14:42 de ***@***.***:

**Comment by vitobotta** [comment]
Hi, sorry for the long delay but I haven't had a chance to check PRs before today unfortunately.

With my last update in June or so I made it possible to configure the URLs for the manifests, so this part is already covered. See other comments as well.

Would you like to fix the PR?

**Comment by vitobotta** [comment]
Hi @DaanVanVugt , are you still interested in completing this PR? :)

**Comment by DaanVanVugt** [comment]
Hi @vitobotta, we ended up going in a different direction, manually setting up networking and k3s for our baremetal workers. Feel free to close / take over this.

**Comment by vitobotta** [comment]
Thanks for the update @DaanVanVugt

**Pull request closed without merging**
