### PR TITLE
fix error handling at server creation

### PR DESCRIPTION
**Pull request by DrBu7cher**

### CODE REVIEW

**Comment by vitobotta** [comment]
Can you please add a description to the PR? Thanks.

**Comment by vitobotta** [comment]
I re-checked the PR and I am gonna close it because I am going to revamp error handling in general in the next version.

**Comment by DrBu7cher** [comment]
Hey, when is the next version going to be rolled out? I have more improvements to date and probably there will be even more, since I am implementing this gem into my productive systems at the moment.
Is any PR then unnecessary until you revamped stuff?
BR

**Comment by vitobotta** [comment]
I'm not sure because I work on it when I have free time. If you have good improvements to share then of course feel free to open PRs and I will check them 🙂

**Pull request closed without merging**
