### PR TITLE
Big refactoring

### PR DESCRIPTION
**Pull request by vitobotta**

### CODE REVIEW

**Comment by jpetazzo** [comment]
Would you like us to test that version of the code and report issues if we find any? Or is that too soon?

**Comment by vitobotta** [comment]
> Would you like us to test that version of the code and report issues if we find any? Or is that too soon?

That would be nice but yes, it's a bit soon. I still need to finish some stuff for 2.0 https://github.com/users/vitobotta/projects/4

**Comment by psavva** [comment]
@vitobotta  let us know if we can do anything to help test and confirm this major refactoring, if you want to make it available for the wider public.

**Comment by vitobotta** [comment]
> @vitobotta let us know if we can do anything to help test and confirm this major refactoring, if you want to make it available for the wider public.

Thanks! I will definitely need some help testing because I have changed quite a bit of everything basically. I am gonna spend more time on this in the coming weekend. I hope to release v2 soon. :)

Once I am ready/almost ready I'll create a discussion to invite anyone who can help with testing, so stay tuned.

**Comment by vitobotta** [comment]
@jpetazzo @psavva Hi! If you are available to help with testing v2 please let me know/confirm in this discussion https://github.com/vitobotta/hetzner-k3s/discussions/385.

I still need to finish some things but I would like to know in advance who can help with this. Thanks

**Comment by psavva** [comment]
> @jpetazzo @psavva Hi! If you are available to help with testing v2 please let me know/confirm in this discussion https://github.com/vitobotta/hetzner-k3s/discussions/385.
> 
> I still need to finish some things but I would like to know in advance who can help with this. Thanks

Absolutely yes :)

Please let me know what you need, and I'm ready to test

**Comment by vitobotta** [comment]
> > @jpetazzo @psavva Hi! If you are available to help with testing v2 please let me know/confirm in this discussion #385.
> > I still need to finish some things but I would like to know in advance who can help with this. Thanks
> 
> Absolutely yes :)
> 
> Please let me know what you need, and I'm ready to test

Awesome. I added some scenarios to test to the discussion I linked to, so you could check some of those. But there are many changes across the board so we'd need to test a bit of everything really. I have tested a lot myself of course, but it's good if more eyes try the new version before it's considered final. Thanks!

**Comment by ajinkyajawale14499** [comment]
- working config.yaml

```
hetzner_token: QRRBcYzIQnEugjcS2J2gV3ohoL8U9gDWhLsF05nVqlCF7LrrAuRjvsJjVZoHt5KK
cluster_name: policymart-k3s
kubeconfig_path: "~/.kube/config"
k3s_version: v1.30.2+k3s2

public_ssh_key_path: "~/.ssh/id_rsa_policymart_ai.pub"
private_ssh_key_path: "~/.ssh/id_rsa_policymart_ai"


ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0

networking:
  ssh:
    port: 22
    use_agent: false # set to true if your key has a passphrase
    public_key_path: "~/.ssh/id_rsa_policymart_ai.pub"
    private_key_path: "~/.ssh/id_rsa_policymart_ai"
  allowed_networks:
    ssh:
      - 0.0.0.0/0
    api: # this will firewall port 6443 on the nodes; it will NOT firewall the API load balancer
      - 0.0.0.0/0
  public_network:
    ipv4: true
    ipv6: true
  private_network:
    enabled : true
    subnet: 10.0.0.0/16
    existing_network_name: ""
  cni:
    enabled: true
    encryption: false
    mode: flannel

schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx21
  instance_count: 1
  location: nbg1
worker_node_pools:
- name: small-static
  instance_type: cpx21
  instance_count: 1
  location: hel1
- name: small-autoscaled
  instance_type: cpx21
  instance_count: 1
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 1

embedded_registry_mirror:
  enabled: true

datastore:
  mode: etcd # etcd (default) or external
  external_datastore_endpoint: postgresql://username:dbname@host:port/postgres
```
- add `ipv4` and `ipv6` along with port `any` in your latest created k3s firewall inbound rules

**Comment by Sheldan** [comment]
You had your hetzner token visible, even if you edited it now. Its still visible in the history, I would reset it now.

**Comment by ajinkyajawale14499** [comment]
This worked for me...
```
hetzner_token: api_token
cluster_name: k3s
kubeconfig_path: "~/.kube/config"
k3s_version: v1.26.4+k3s1

public_ssh_key_path: "~/.ssh/id_rsa.pub"
private_ssh_key_path: "~/.ssh/id_rsa"


ssh_allowed_networks:
  - 0.0.0.0/0
api_allowed_networks:
  - 0.0.0.0/0

additional_packages:
- haproxy
post_create_commands: ## Downloads an HAProxy configuration file for port 80/443
- curl -o /etc/haproxy/haproxy.cfg https://gist.githubusercontent.com/laszlocph/61642778fb61e3d7c1766d31e676c0f7/raw/bf836c73ce24b07b2423251316e6f030ada6b3c9/haproxy.cfg
- service haproxy reload

schedule_workloads_on_masters: false
masters_pool:
  instance_type: cpx21
  instance_count: 1
  location: nbg1
worker_node_pools:
- name: small-static
  instance_type: cpx21
  instance_count: 1
  location: hel1
- name: small-autoscaled
  instance_type: cpx21
  instance_count: 1
  location: fsn1
  autoscaling:
    enabled: true
    min_instances: 0
    max_instances: 1

embedded_registry_mirror:
  enabled: true

datastore:
  mode: etcd # etcd (default) or external
  external_datastore_endpoint: postgresql://username:password@host:port/postgres
```

don't forget to add ipv4 and ipv6 under rules along with port any for your latest created k3s firewall

**Comment by vitobotta** [comment]
> This worked for me...
> 
> ```
> hetzner_token: api_token
> cluster_name: k3s
> kubeconfig_path: "~/.kube/config"
> k3s_version: v1.26.4+k3s1
> 
> public_ssh_key_path: "~/.ssh/id_rsa.pub"
> private_ssh_key_path: "~/.ssh/id_rsa"
> 
> 
> ssh_allowed_networks:
>   - 0.0.0.0/0
> api_allowed_networks:
>   - 0.0.0.0/0
> 
> additional_packages:
> - haproxy
> post_create_commands: ## Downloads an HAProxy configuration file for port 80/443
> - curl -o /etc/haproxy/haproxy.cfg https://gist.githubusercontent.com/laszlocph/61642778fb61e3d7c1766d31e676c0f7/raw/bf836c73ce24b07b2423251316e6f030ada6b3c9/haproxy.cfg
> - service haproxy reload
> 
> schedule_workloads_on_masters: false
> masters_pool:
>   instance_type: cpx21
>   instance_count: 1
>   location: nbg1
> worker_node_pools:
> - name: small-static
>   instance_type: cpx21
>   instance_count: 1
>   location: hel1
> - name: small-autoscaled
>   instance_type: cpx21
>   instance_count: 1
>   location: fsn1
>   autoscaling:
>     enabled: true
>     min_instances: 0
>     max_instances: 1
> 
> embedded_registry_mirror:
>   enabled: true
> 
> datastore:
>   mode: etcd # etcd (default) or external
>   external_datastore_endpoint: postgresql://username:password@host:port/postgres
> ```
> 
> don't forget to add ipv4 and ipv6 under rules along with port any for your latest created k3s firewall

This is a PR about the upcoming v2 of the tool, please see the discussion at https://github.com/vitobotta/hetzner-k3s/discussions/385 for details on some changes that you need to make to the configuration to make it compatible with the new version. Also please open an issue (rather than commenting in this PR) if you run into a problem with the new version. Thanks!

**Pull request merged**
