### PR TITLE
Add build instructions

### PR DESCRIPTION
**Pull request by jpetazzo**
I suppose that these are obvious for someone who is familiar with Crystal; but I wasn't, and it took me a while to figure out how to build the code to test my changes :)

I've also added a working_dir to the Compose file, so that the user is placed directly in the source directory. I hope this won't affect other uses (e.g. inside VSCode).

### CODE REVIEW

**Comment by vitobotta** [comment]
Thanks for the PR! However since I have already added configuration for VsCode's dev container feature which is awesome compared to just using compose, would you mind updating the README on how to use that too?

**Comment by vitobotta** [comment]
I'll just merge this for now since it's small, and will make adjustments later if needed. Thanks again!

**Comment by jpetazzo** [comment]
It took me a while because VSCode didn't work as expected, but I figured it out :)

I opened another PR (#357) with the VSCode explanations.

Hopefully that'll help other potential contributors :D

**Comment by vitobotta** [comment]
> It took me a while because VSCode didn't work as expected, but I figured it out :)
> 
> I opened another PR (#357) with the VSCode explanations.
> 
> Hopefully that'll help other potential contributors :D

Thanks!

**Pull request merged**
