### PR TITLE
Using server name to reduce return list. fixes vitobotta/hetzner-k3s#184

### PR DESCRIPTION
**Pull request by quorak**
Fixes return lists without the actual server when more than 25 entries.

### CODE REVIEW

**Comment by vitobotta** [comment]
Hi @quorak apologies for the delay, I have been too busy with the day job. Thanks for your contribution! It's a awesome fix in its simplicity. I forgot to check PRs before releasing a new version today but will merge and make a small release in the coming days.

**Comment by vitobotta** [comment]
Actually there is a small conflict, do you mind updating the pr? Thanks :)

**Comment by quorak** [comment]
perfect. done.

**Comment by vitobotta** [comment]
Thanks @quorak !

**Pull request merged**
